spring:
  application:
    name: CachingWithRedisInSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/cachingWithRedis #I manually created this SCHEMA in the database before application could start
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9696
api:
  endpoint:
    base-url: /api/v1

  redis:
    host: localhost
    port: 6379
    #timeout: 2000
    #cache-timeout: 3600
    cache-prefix: CachingWithRedisInSpringBoot
  cache:
    type: REDIS
  jackson:
    serialization:
      write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.

