spring:
  application:
    name: CachingWithRedisInSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:5432/cachingWithRedis #I manually created this SCHEMA in the database before application could start
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9696
api:
  endpoint:
    base-url: /api/v1
